export interface VocabularyItem {
  id: string;
  chinese: string;
  pinyin: string;
  english: string;
  category: VocabularyCategory;
  hint: string;
  spanish?: string;
}

export type VocabularyCategory = 
  | 'pronouns'
  | 'family'
  | 'numbers'
  | 'time'
  | 'countries'
  | 'food'
  | 'animals'
  | 'verbs'
  | 'other'
  | 'names'
  | 'emotions'
  | 'objects'
  | 'places'
  | 'concepts'
  | 'phrases'
  | 'grammar'
  | 'drinks'
  | 'transportation'
  | 'actions'
  | 'adjectives'
  | 'measure'
  | 'technology'
  | 'entertainment'
  | 'adverbs'
  | 'question words'
  | 'work'
  | 'language'
  | 'conjunctions'
  | 'modal verbs'
  | 'directions'
  | 'professions'
  | 'relationships'
  | 'finance'
  | 'politeness'
  | 'people'
  | 'identity'
  | 'greetings'
  | 'prepositions'
  | 'clothing'
  | 'furniture'
  | 'activities'
  | 'age'
  | 'body'
  | 'business'
  | 'celebrations'
  | 'colors'
  | 'determiners'
  | 'education'
  | 'health'
  | 'media'
  | 'nature'
  | 'ordinals'
  | 'sports'
  | 'titles'
  | 'weather'
  | 'languages'
  | 'appliances'
  | 'arts'
  | 'books'
  | 'documents'
  | 'geography'
  | 'life events'
  | 'money'
  | 'plants'
  | 'politics'
  | 'seasons'
  | 'senses'
  | 'shapes'
  | 'subjects'
  | 'tastes'
  | 'travel'
  | 'utensils'
  | 'behavior'
  | 'communication'
  | 'culture'
  | 'elements'
  | 'events'
  | 'expressions'
  | 'information'
  | 'landmarks'
  | 'medical'
  | 'office'
  | 'skills'
  | 'society'
  | 'tools'
  | 'measurement';

export interface Progress {
  itemId: string;
  correctCount: number;
  incorrectCount: number;
  lastPracticed: Date;
}